ci:
  collect:
    url:
      - https://cloutdumpster.com/          # prod
      - https://cloutdumpster.com/feed
      - https://cloutdumpster.com/profile/demoUser
    numberOfRuns: 3
    settings:
      preset: desktop
  assert:
    assertions:
      categories:performance: ['warn', {minScore: 0.8}]
      categories:accessibility: ['error', {minScore: 0.9}]
      categories:best-practices: ['warn', {minScore: 0.8}]
      categories:seo: ['warn', {minScore: 0.8}]
      categories:pwa: ['warn', {minScore: 0.8}]
  upload:
    target: filesystem
    outputDir: ./lhci-results
